version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=eps
    ports:
      - "3306:3306"
    container_name: db_mysql
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: eps:v0.2
    command: /code/boot.sh
    volumes:
      - ./backend/code/:/code/
      - ./frontend/:/var/www/eps/
      - ./dataset/:/dataset/
    ports:
      - "8000:80"
      - "8080:8080"
    depends_on:
      - db
    container_name: backend



